name: Build

on:
  - push

jobs:
  build-dsk-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: ./forge all

  build-and-test-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build and test macOS application
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
        run: _
          xcodebuild -project Space\ Bandits/Space\ Bandits.xcodeproj -scheme "Space Bandits" test
          xcodebuild -project Space\ Bandits/Space\ Bandits.xcodeproj -scheme "Space Bandits" build CONFIGURATION_BUILD_DIR=`pwd`/build
