name: Make a New Release

on:
  push:
    tags:
      - '*'

jobs:
  build-dsk-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build *.dsk images
        run: ./forge all

      - name: 'Upload *.dsk Images'
        uses: actions/upload-artifact@v2
        with:
          name: dsk-images
          path: build/*.DSK
          retention-days: 1


  upload-artifacts:
    runs-on: ubuntu-latest
    needs: build-dsk-images
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2

      - name: Get the tag
        run: |
          echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Create a releae
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./dsk-images/*.DSK"
          allowUpdates: true
          draft: true
          name: "${{ format('{0} {1}', env.REPO_NAME, env.RELEASE_TAG) }}"
